#ifndef __ERROR
#define __ERROR
/* -----------------------------------------------------------------
 *   Definiciones de textos de errores.
 * ----------------------------------------------------------------- */
typedef struct {
            int error;
            int nivel;
            char * descripcion;
         }s_lista_errores;

s_lista_errores ListaERROR[] = {
	{ERR_DESCONOCIDO,ERROR_RED,TEXTO_ERR_DESCONOCIDO},
	{ERR_MALLOC,ERROR_FISICO,TEXTO_ERR_MALLOC},
	{ERR_CODIFICA,ERROR_FISICO,TEXTO_ERR_CODIFICA},
	{ERR_DECODIFICA,ERROR_FISICO,TEXTO_ERR_DECODIFICA},
	{ERR_PEDAZO_FUERA_SECUENCIA,ERROR_RED,TEXTO_ERR_PEDAZO_FUERA_SECUENCIA},
	{ERR_CORREOS_COGER,ERROR_FISICO,TEXTO_ERR_CORREOS_COGER},
	{ERR_CORREOS_SELECT,ERROR_FISICO,TEXTO_ERR_CORREOS_SELECT},
	{ERR_CORREOS_MANDAR,ERROR_FISICO,TEXTO_ERR_CORREOS_MANDAR},
	{ERR_BIND_SOCKET,ERROR_FISICO,TEXTO_ERR_BIND_SOCKET},
	{ERR_DIR_MULTICAST,ERROR_FISICO,TEXTO_ERR_DIR_MULTICAST},
	{ERR_CREAR_SOCKET,ERROR_FISICO,TEXTO_ERR_CREAR_SOCKET},
	{ERR_DIRECCION,ERROR_RED,TEXTO_ERR_DIRECCION},
	{ERR_RESPUESTA,ERROR_RED,TEXTO_ERR_RESPUESTA},
	{ERR_TIMEOUT,ERROR_ENLACE,TEXTO_ERR_TIMEOUT},
	{ERR_SIN_METODO,ERROR_ENLACE,TEXTO_ERR_SIN_METODO},
	{ERR_VERSION,ERROR_ENLACE,TEXTO_ERR_VERSION},
	{ERR_DESAPLANA,ERROR_ENLACE,TEXTO_ERR_DESAPLANA},
	{ERR_ACK_TIMEOUT,ERROR_ENLACE,TEXTO_ERR_ACK_TIMEOUT},
	{ERR_BUZON,ERROR_SESION,TEXTO_ERR_BUZON}};

#define MAX_LISTA sizeof(ListaERROR)/sizeof(s_lista_errores)
#endif /* __ERROR*/
