/* <MESA:01:@(#):MwillyfrSB2w:pds:1.1:021028195850:willy:1 35 8505:MESA> */
#define ERR_SIN_MEMORIA      " Error <malloc>, not memory to work " 
#define ERR_NRO_PARAMETROS   " ERROR NRO. OF PARAMETERS "
#define ERR_PARAMETROS       " ERROR PARAMETERS "
#define ERR_OPCION_NO_VALIDA " Invalid Option "
#define ERR_EXT_F_FUENTE   " Invalid file extension, must be .src"
#define ERR_ABRIR_F_FUENTE   " Can't open source file"
#define ERR_ABRIR_F_DESCRIP  " Can't open Description file"
#define ERR_ABRIR_F_PROTO    " Can't open prototype file "
#define ERR_SCANER           " Scanner ERROR "
#define FICH_DESC_VACIO      " Description file empry "
#define TOKEN_MUY_GRANDE     " Token to big in line " 
#define ERR_PARSER           " Parser Error " 
#define ERR_METODO_SIN_CLASE " Method without Clase "
#define ERR_NOM_CONST_LARGA  " Constant name Too long "
#define ERR_VAL_CONST_LARGA  " Value of constant too long "
#define ERR_CONST_SIN_ASIG   " Unassigned constant " 
#define ERR_SIMBOLO_INESPERADO  " Invalid symbol "
#define ERR_CADENA           " String: "
#define ERR_T_IN             " ""IN"" "
#define ERR_T_OUT            " ""OUT"" "
#define ERR_T_CONSTANTE      " ""CONST"" "
#define ERR_T_IGUALDAD       " ""="" "
#define ERR_EN_LINEA         " at line : "  
#define ERR_FIN_FICHERO      " Unexpeted en of file "
#define ERR_PRI_CLASE       " lack <{> " 
#define ERR_P_PARAMETROS     " <::> expected and not found " 
#define ERR_GENERACION       " Error Generating : "
#define ERR_FIN_ARRAY        " Don't end ARRAY "
#define ERR_VALOR_ARRAY_ERRONEO  "Wrong Array dimension "
#define ADVERTENCIA_SRC      "/*\nGenerated Code by SRC, don't touch \n*/"
